server:
  port: 8085
spring:
  application:
    name: ly-user-service
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  redis:
    host: 192.168.47.128
  rabbitmq:
    host: 192.168.1.100
    username: leyou
    password: leyou
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
