server:
  port: 8082
spring:
  application:
    name: ly-upload
  servlet:
    multipart:
      max-file-size: 5MB #限制文件上传大小
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    ip-address: 127.0.0.1
    prefer-ip-address: true
leyou:
   upload:
      allowType:
        - image/jpeg
        - image/gif
        - image/png
      url: http://image.leyou.com/
fdfs:
  so-timeout: 1501 # 超时时间
  connect-timeout: 601 # 连接超时时间
  thumb-image: # 缩略图
    width: 60
    height: 60
  tracker-list: # tracker地址：你的虚拟机服务器地址+端口（默认是22122）
    - 192.168.47.128:22122