server:
  port: 8081
spring:
  application:
    name: item-service
  rabbitmq:
    host: 192.168.1.100
    username: leyou
    password: leyou
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000s
        max-interval: 30000s
        multiplier: 2
      exchange: leyou.item.exchange
    publisher-confirms: true
  datasource:
    url: jdbc:mysql://localhost:3306/yun6
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
      lease-renewal-interval-in-seconds: 5 # 5秒钟发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
mybatis:
  configuration:
    log-impl:  org.apache.ibatis.logging.stdout.StdOutImpl